name: Deploy to staging

on:
  push:
    branches:
      - dev

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster

    steps:
      - name: Deploy via SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY_DEVELOPER1 }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

          ssh -i ~/ssh_key ubuntu@13.233.118.247 << 'EOF'
            set -e

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            nvm use 22
            export PATH="$PATH:$(npm bin -g)"

            cd excalidraw-clone
            git pull origin dev

            pnpm install
            pnpm run build

            pm2 restart excalidraw-fe-staging
            pm2 restart excalidraw-http-staging
            pm2 restart excalidraw-ws-staging
          EOF
