name: Deploy to staging

on:
  push:
    branches:
      - dev

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY_DEVELOPER1 }}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          echo "${{ secrets.KNOWN_HOSTS }}" &> /home/runner/.ssh/known_hosts
          chmod 700 /home/runner/ssh_key
          ssh -i ~/ssh_key ubuntu@13.233.118.247 -t "
          export NVM_DIR=\"\$HOME/.nvm\" &&
          [ -s \"\$NVM_DIR/nvm.sh\" ] && . \"\$NVM_DIR/nvm.sh\" &&
          nvm use 22 &&
          cd excalidraw-clone &&
          git pull origin dev &&
          pnpm install &&
          pnpm run build &&
          pm2 restart excalidraw-fe-staging &&
          pm2 restart excalidraw-http-staging &&
          pm2 restart excalidraw-ws-staging
          "

