name: Deploy to staging

on:
  push:
    branches:
      - dev



jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_DEVELOPER1 }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          
      - name: Add server to SSH known hosts
        run: |
          ssh-keyscan -H 52.66.242.186 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/ssh_key ubuntu@52.66.242.186 << 'EOF'
            set -e

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            nvm use 22
            export PATH="$PATH:$(npm bin -g)"

            command -v pnpm >/dev/null 2>&1 || npm install -g pnpm
            command -v pm2 >/dev/null 2>&1 || npm install -g pm2
            cd excalidraw-clone
            git pull origin dev

            pnpm install
            pnpm run build

            pm2 restart excalidraw-frontend
            pm2 restart http-backend
            pm2 restart ws-backend
          EOF
